### ISSUE TITLE
Plugins don't show after installing

### ISSUE THREAD

**Issue by ruthger** [mclarkson/obdi#24]
After adding the repositories and selecting the plugins to be installed they don't show up in obdi. When I take a look in /usr/share/obdi/static/plugin I see the different directories. Within the the directories I noticed that the go sources haven't been compiled. But that again the salt plugin doesn't have go sources, only html.

I'm running Archlinux with go 2:1.4.2

If you need more info I will try to get it for you.

**Comment by mclarkson** [comment]
Thanks @ruthger, I will try to install the packages you built for Arch:
https://aur.archlinux.org/packages/obdi-git/

Just in case you know, are there LXC (linux container) templates or images for Arch?
If not I will use the vagrant box, 'terrywang/archlinux' - Should be okay to use do you think?

Any chance you could provide the Arch command to install obdi, once I have Arch installed?

**Comment by mclarkson** [comment]
Thanks for the repository info you sent privately.

Things I did:

Installed Arch using vagrant. Then:

```
mkdir /etc/obdi/certs
mkdir /var/cache/obdi

openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 \
    -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=snakeoil" \
    -keyout /etc/obdi/certs/key.pem -out /etc/obdi/certs/cert.pem

journalctl -fu obdi
```

Web browsed, FIrefox 36.0.4, to '/manager/run'
Logged in with admin/admin
Plugins -> Manage Repositories: Pasted `https://github.com/mclarkson/obdi-core-repository.git`.
Add, Go Back, Add Plugin
Add (on systemjobs)
Installing... (no log output during wait, which would be useful.)

Added a user (only added info on the first tab)
Web Browsed to '/manager/run'
Logged in as the new user
'System Jobs' is in the left bar.

Back to the Admin interface and added `https://github.com/mclarkson/obdi-salt-repository.git`
Then installed all six plugins at once.
Logged back into the Run interface.
All plugins were shown. (Salt group expands on click)

Only two errors were shown in the obdi log.

```
Apr 02 08:28:15 archlinux.vagrant.vm obdi[4252]: 2015/04/02 08:28:15 http: TLS handshake error from 127.0.0.1:50860: remote error: unknown certificate authority
Apr 02 08:28:15 archlinux.vagrant.vm obdi[4252]: 2015/04/02 08:28:15 http: TLS handshake error from 127.0.0.1:50861: remote error: unknown certificate authority
```

Obdi also logs to the system log (syslog) but it's not installed in the vagrant box.

So, for me, using your package, it was fairly painless and worked. It's good that an up-to-date golang is installed.

The go sources are compiled on-demand, so won't be compiled at all with the steps I used.

I noticed, in obdi.conf:

```
# The path for additional sqlite3 plugin databases.
plugin_database_path = "/var/lib/obdi/plugins/"
```

But the created directory is:

```
/var/lib/obdi/plugin/
```

I didn't fix the obdi.conf or directory name since it doesn't get that far anyway.

Maybe you could also try the above in Vagrant.

Or, maybe it doesn't like the Web Browser. I only really use Firefox, but Chrome works.

Also, It might be a problem if the Web Browser is on a slow machine - I added a 500ms delay before showing the side menu otherwise sometimes it wouldn't show. To increase the delay edit:
`/usr/share/obdi/static/js/controllers/sidebar.js`
At the top, change 500 to 5000, as below, for a 5 second delay for testing.

```
// ------------------------------------------------------------------------
 mgrApp.directive('onLastRepeat', function () {
 // ------------------------------------------------------------------------
   return function(scope, element, attrs) {
       if (scope.$last) setTimeout(function(){
         scope.$emit('onRepeatLast', element, attrs);
     }, 5000);
   };
 });
```

**Comment by ruthger** [comment]
Mark,

I have updated the PKGBUILD with the following steps:
- Create the /etc/obdi/certs directory
- Create the /var/cache/obdi directory
- Corrected /var/lib/obdi/plugins directory
- Added the openssl cert and key to the package

The new package is available in my private repository. I will try out 
the new package this tonight in a clean setup.

What did you mean with "It's good that an up-to-date golang is 
installed." and "The go sources are compiled on-demand, so won't be 
compiled at all with the steps I used."?? I should not compile the go 
sources within the packages, but on installing??

And should I try to create two separate packages for the obdi and 
obdi-worker?? Is obdi-worker depending on obdi??

With regards,

Ruthger Gubbels

**Comment by mclarkson** [comment]
On Debian Wheezy the package is golang version 1.0.2, on Ubuntu Trusty the package is golang-go version 1.2.1, CentOS/RedHat it needs EPEL and is golang version 1.3.3, Arch .. golang version 1.4.2 (i.e. up-to-date)

Obdi plugins work by forking a go executable then connecting to it over RPC (takes about 3ms). This allows a plugin to extend the REST interface for the main obdi process. The go executable it tries to run is based on the REST path. If it doesn't find the go executable then it will try to compile it, but only when it needs it. It will also recompile the go executable if it finds that the go source is newer than the executable. So this happens transparently, and the first time a go plugin is used there may be a noticeable delay (when the plugin uses sqlite the delay is big (~30s) because it has to compile C source code first).

Yes, there should be two packages. Obdi-worker is not dependent on obdi. There should be one obdi-worker with obdi (not a requirement), and an obdi-worker (with no obdi) for each environment. Obdi-worker needs /etc/obdi-worker/certs too. For the Salt plugins the obdi-worker will sit with the salt master, then it uses Salt to contact Minions, to do discovery, to get job status etc., by running bash or python scripts on the salt master. The whole script is sent each time in a REST request to the obdi-worker, so not stored on the obdi-worker machine, then updates will happen instantly.

**Comment by ruthger** [comment]
Mark,

Can you tell me the directories I need for the obdi and obdi-worker? 
And update the obdi-worker.conf to search the certs in the correct 
place?

My server isn't available at the moment (network not responding and I 
not at home). But I will try to create the packages for obdi and 
obdi-worker. If I have to I will try to do the same for the debian and 
redhat packages. I have no experience with git so the pull request may 
take a bit longer.

With regards,

Ruthger

**Comment by mclarkson** [comment]
I did update the debian/ubuntu packages: 0130886ea730a2a9a4c6e1faa5496fb3e40554d0, fa6e425865c6dcbeee1d46fb9e4e4012a400bc38, c0963c28ceda774ea23e998a3c92b55aaad0331f, 61f494d86d1d56ab7b2806cc52615faa19d60228, and d1596067a890efe016e772defa12018929e504a6. 

I think the only thing that needs doing is cert creation for the RPM package, #21.

**Comment by ruthger** [comment]
Mark,

I have separated obdi and obdi-worker for Archlinux. 
https://aur.archlinux.org/packages/obdi-git/
https://aur.archlinux.org/packages/obdi-worker-git/

On a clean install the packages and plugins are working perfectly. I only cannot get it to work on my salt server. But that's my problem.

So I'm closing the issue now. Thanks for your support and hopefully we will see some new developments in the near future.

**Comment by mclarkson** [comment]
Hi Ruthger,
I've finally written some documentation for Ubuntu [here](https://github.com/mclarkson/obdi-salt-repository/blob/master/docs/ubuntu_guide.md). It might help you to get Obdi running with Salt on Arch.

Cheers!
Mark.

**Comment by mclarkson** [comment]
Hi Ruthger. I just wondered if you still have the systemd files? The link https://aur.archlinux.org/packages/obdi-git/ is empty now. If you still have them please send them thanks!

**Comment by ruthger** [comment]
Mark,

Thanks to my prive git repository I could retrieve them.

With regards,

Ruthger

-- obdi.service
[Unit]
Description=Obdi

[Service]
Type=simple
Restart=always
PIDFile=/var/run/obdi.pid
ExecStart=/usr/bin/obdi

[Install]
WantedBy=multi-user.target

-- obdi-worker.service
[Unit]
Description=Obdi

[Service]
Type=simple
Restart=always
PIDFile=/var/run/obdi-worker.pid
ExecStart=/usr/bin/obdi-worker

[Install]
WantedBy=multi-user.target

Op 15-11-2016 om 12:57 schreef Mark Clarkson:

**Comment by mclarkson** [comment]
Nice one! Thanks a bunch Ruthger. I'll use those for Centos 7.
